#应用容器配置
server:
  port: 12304
#日志配置
logging:
  level:
    root: info

#项目配置
security:
  user:
    name: hpx_config
    password: hpx123456

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://hpx:hpx123456@localhost:12302/eureka/
#spring配置
spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-pri-tools.hypex.io/root/spring-cloud-config.git #配置Git仓库位置。
          searchPaths: config-repo/hpx/ #配置仓库路径下的相对搜索位置，可以配置多个。
          username: deployer_2018_jp@163.com #访问 Git 仓库的用户名。
          password: deployer #访问 Git 仓库的用户密码。
          ###如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写。
          label: master #配置仓库的分支
          basedir: /opt/spring-cloud-config
          clone-on-start: true